apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-hello
  template:
    metadata:
      labels:
        app: python-hello
    spec:
      containers:
        - name: python-hello-app-container
          image: python-hello-app:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 5000